### ISSUE TITLE
Texture

### ISSUE THREAD

**Issue by georgino-ccrp** [mikigoalie/lsrp_vehicleshop#13]
hi, i have a bug that sometimes the textures around the vehicle shop starts bugging..
I was wondering if its just me or if it does something else
The textures start bugging if you are scrolling too fast

**Comment by PabloSchar** [comment]
I have the same problem. The solution would be that until you charge the vehicle does not let you do any interaction but do not know how to do that in ox lib menu

**Comment by mikigoalie** [comment]
Fixed it latest versions
