### ISSUE TITLE
Instead of using licenses, add an option of having an item as requirement

### ISSUE THREAD

**Issue by Esterze** [mikigoalie/lsrp_vehicleshop#14]
Add an option to require an item before purchasing a vehicle, this will enhance the roleplay

**Comment by mikigoalie** [comment]
I don't think this makes much sense, I will add a hook though

**Comment by mikigoalie** [comment]
https://github.com/mikigoalie/lsrp_vehicleshop/blob/9be171dbb919cc57c5252c05902c6fef98eecbe2/server/bridge/framework.lua#L35

Here you can hook your own logic, adding a inv check for example

**Comment by Esterze** [comment]
I ain't really that good when it comes to coding. I hope you consider adding it one day.
