### ISSUE TITLE
Plate text is not generated according to ESX

### ISSUE THREAD

**Issue by KamiliaBlow** [mikigoalie/lsrp_vehicleshop#19]
When you buy a car, your license plate number remains a multi-digit number instead of being the standard "ABC 123" number.

**Comment by KamiliaBlow** [comment]
I have the latest version of ESX Legacy running, however when I buy the machine, the number looks like this
![image](https://github.com/mikigoalie/lsrp_vehicleshop/assets/25077548/b5a31f39-d9e8-4d85-a18e-2a06245a9b5a)

If this script does generate a number like "VDG 483". Something's not working for me 🤔

**Comment by mikigoalie** [comment]
Currently does not support custom plate format, cores usually handle that and so does ESX. When you spawn a vehicle, ESX handles plate creation.

**Comment by mikigoalie** [comment]
Late response, but it is fixed with latest version
