### ISSUE TITLE
An error ocured while saving this vehicle

### ISSUE THREAD

**Issue by Jeffrey-jumbo** [mikigoalie/lsrp_vehicleshop#20]
ESX Version: 1.6.0

Error: [script:lsrp_vehicles] SCRIPT ERROR: @lsrp_vehicleshop/server/main.lua:109: attempt to index a nil value (field 'OneSync')
[script:lsrp_vehicles] > callbackResponse (@ox_lib/callback/server.lua:60)
[script:lsrp_vehicles] > handler (@ox_lib/callback/server.lua:76)
[script:lsrp_vehicles] > rawQuery (@oxmysql/dist/build.js:25056)
[script:lsrp_vehicles] > processTicksAndRejections (node:internal/process/task_queues:96)

The line of the error:

        ESX.OneSync.SpawnVehicle(data.vehicleModel, Config.vehicleShops[_shopIndex].vehicleSpawnCoords.xyz, Config.vehicleShops[_shopIndex].vehicleSpawnCoords.w, _vehProps, function(NetworkId)

Pls help me!

**Comment by mikigoalie** [comment]
Outdated framework. You havee to update ESX
