### ISSUE TITLE
SCRIPT ERROR: @lsrp_vehicleshop/client/main.lua:74: No such export Search in resource ox_inventory

### ISSUE THREAD

**Issue by yiruzu** [mikigoalie/lsrp_vehicleshop#3]

**Comment by mikigoalie** [comment]
https://overextended.github.io/docs/ox_inventory/Functions/Client/Inventory/Search

Make sure your inventory resource is running

**Comment by yiruzu** [comment]
Is the ox_inventory a dependencie?

**Comment by mikigoalie** [comment]
Good point :D What inventory are you using?

**Comment by yiruzu** [comment]
I Use the Chezza Inventory V3 and yes can you please implement a ESX Cash Check because not everyone wants to use ox_inventory

**Comment by mikigoalie** [comment]
Decided not to support since I don't use other inv than OX's. Feel free to make a PR in future to support other inventories or frameworks
