### ISSUE TITLE
regarding detect license

### ISSUE THREAD

**Issue by deputystrand** [mikigoalie/lsrp_vehicleshop#5]
is it possible to make the detection for the car license as item
cause my car license i using the pickle documents script and is a item 
i would like to make it to detect if the item is in the player inventory a not

**Comment by mikigoalie** [comment]
Hey, the car license thingy should be working by default through db licenses. However, I can rewrite the function and leave it in bridge so you can hook it yourself

**Comment by deputystrand** [comment]
nice
cause i would like id to detect item as my driving license is an item

**Comment by mikigoalie** [comment]
Added a hook bridge for detecting licenses
