### ISSUE TITLE
preview cars wont delete

### ISSUE THREAD

**Issue by deputystrand** [mikigoalie/lsrp_vehicleshop#7]
i found a issue when i preview the cars in the vehicleshop when i backspace to cancel without purchasing the vehicle model stuck there it wont disappear

**Comment by mikigoalie** [comment]
Cancelling purchase will take you back to main menu, unless you edited something, it should work fine

**Comment by deputystrand** [comment]
i havent edited anything 
beside the location of the shop and the preview cars model only

**Comment by deputystrand** [comment]
i think i will discuss with u in the overextended discord ?
