### ISSUE TITLE
no spawn npc

### ISSUE THREAD

**Issue by JancsiOfficial** [mikigoalie/lsrp_vehicleshop#8]
I can't see the npc anywhere. no spawn

**Comment by mikigoalie** [comment]
Redownload release please

**Comment by JancsiOfficial** [comment]
Unfortunately it still does not spawn down

**Comment by JancsiOfficial** [comment]
![image](https://github.com/mikigoalie/lsrp_vehicleshop/assets/123206097/bd410aa8-bf60-403a-b5ae-185e7eedf3ca)
just spawn the first coords's car. I change the npc spawn coords but no spawn the npc

**Comment by JancsiOfficial** [comment]
Or I download 1.9.2 realase verzion?

**Comment by mikigoalie** [comment]
I have no idea what you're trying to report here.. Just set your configs?

**Comment by JancsiOfficial** [comment]
I use changed or default settings but the npc no spawn and I can't open a shop with E keybind or ox_target. I try to riport this

**Comment by JancsiOfficial** [comment]
But if I change a coords then no spawn npc
